services:
  frontend:
    image: appimage
    ports:
      - "1111:80"
    depends_on:
      - devopsdb

  backend:
    image: devopsdb
    ports:
      - "3306:3306"
    volumes:
      - mydata:/var/lib/mysql
    deploy:
      resources:
        reservations:
          cpus: "0.5"
          memory: "500M"
        limits:
          cpus: "1"
          memory: "1000M"

volumes:
  mydata:
